### ISSUE TITLE
version `GLIBC_2.34' not found

### ISSUE THREAD

**Issue by Manichee** [cameroncros/discordshim_rs#1]
Did a git pull to get latest code, did a docker compose down, and then docker compose up --build -d. It compiled and downloaded a few programs. All seemed to go well and it said container started. However it stops with an error:

 ```
✔ Network discordshim_rs_default          Created                                                                0.1s 
 ✔ Container discordshim_rs-discordshim-1  Created                                                                0.0s 
Attaching to discordshim_rs-discordshim-1
discordshim_rs-discordshim-1  | /usr/local/bin/discordshim: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/local/bin/discordshim)
discordshim_rs-discordshim-1  | /usr/local/bin/discordshim: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/local/bin/discordshim)
discordshim_rs-discordshim-1  | /usr/local/bin/discordshim: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/local/bin/discordshim)
discordshim_rs-discordshim-1 exited with code 0
```
I am not very familiar with compiling docker containers myself. It was working before the latest code.
**_EDIT_** I tried on another machine and got the same error. Also tried going back a few commits and still have the same error.

**Comment by cameroncros** [comment]
Weird, seems debian base images dont have glibc anymore. I am pushing a fix, will be in main soonish

**Comment by Manichee** [comment]
Back up and running now with the latest commit.

**Comment by cameroncros** [comment]
Fantastic. FWIW, I am pleased to learn that someone is actually doing the self-hosting option, it takes the load off my hosted service.

If you have any feedback on the ease of setup please let me know, I would like to make it as easy as possible.
