### ISSUE TITLE
Discord Integrated Commands / slash no longer working by default

### ISSUE THREAD

**Issue by dogshapedangel** [cameroncros/discordshim_rs#4]
Discord now supports native /slash commands in the interface and this breaks the default configuration of DiscordShim_RS as well as the hosted version. 

While the command symbol can be changed, the ideal path forward would be to update DiscordShim_RS to support Discord's integrated command functionality. 

Discord developer docs for Application Commands: https://discord.com/developers/docs/interactions/application-commands

Also see: https://github.com/cameroncros/OctoPrint-DiscordRemote/issues/256

**Comment by cameroncros** [comment]
The reason I have been hesitant to make this change is that it will intrinsically tie discordshim_rs to OctoPrint_DiscordRemote. I'll have another think/look at this, but if you have a solution, I would be happy to accept contributions.

Can you clarify what you mean by "breaks the default configuration"? I can use `/help` in discord just fine, what is broken? (I tested in Desktop and Android, both work)

**Comment by cameroncros** [comment]
@manedfolf Can you clarify what you mean by "breaks the default configuration"? I can use /help in discord just fine, what is broken? (I tested in Desktop and Android, both work)

With no further details, I am inclined to close this, as I cant fix a breakage that I cant replicate. Please explain how to replicate the breakage.

**Comment by cameroncros** [comment]
@manedfolf With the lack of instructions on how to replicate, I will be closing this off. Please reopen if you can describe how to replicate the bug.
